version: '3.8'

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    hostname: zabbix-server
    ports:
      - "10051:10051" # Porta para os agentes Zabbix
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=12345678 # Altere esta senha!
      - MYSQL_ROOT_PASSWORD=12345678 # Altere esta senha!
      - ZBX_CACHESIZE=2G # Ajuste conforme a necessidade
      - ZBX_STARTPOLLERS=10 # Ajuste conforme a necessidade
      - ZBX_STARTTRAPPERS=5 # Ajuste conforme a necessidade
    volumes:
      # No Windows, os caminhos de volume precisam ser absolutos ou relativos ao docker-compose.yml
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
    depends_on:
      - mysql-server
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    hostname: zabbix-web
    ports:
      - "80:8080" # Porta para o acesso ao frontend Zabbix (HTTP)
      # - "443:8443" # Descomente para HTTPS
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=12345678 # A mesma senha do banco de dados
      - PHP_TZ=America/Sao_Paulo # Ajuste para seu fuso horário
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net

  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    hostname: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=12345678 # Altere esta senha!
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=12345678 # Altere esta senha!
    volumes:
      # No Windows, os caminhos de volume precisam ser absolutos ou relativos ao docker-compose.yml
      - ./zbx_env/mysql_data:/var/lib/mysql
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge